### ISSUE TITLE
Extracting variables in a protocol

### ISSUE THREAD

**Issue by ferlopezm94** [markspanbroek/MockingInSwift#1]
Hi! I'm trying to implement your tips when mocking a CBPeripheral and CBCentralManager. What you explain works fine. But when I try to use the CBPeripheralType in my own classes, I use the delegate of the peripheral, so I try to extract the variables delegate and state in the CBPeripheralType protocol, but then I don't know how to conform to that protocol from the extension of the CBPeripheral because extensions can't contain stored properties. Have you encounter this problem?

**Comment by markspanbroek** [comment]
Hi @ferlopez94, if you define CBPeripheralType as follows:
```swift
protocol CBPeripheralType: class {
    var delegate: CBPeripheralDelegate? { get }
    var state: CBPeripheralState { get }
}
```
Then don't need to do anything special in the protocol extension, because CBPeripheral already conforms to this protocol.
```swift
extension CBPeripheral: CBPeripheralType {}
```
In your mock you can then define stored properties in order to conform to the CBPeripheralType protocol:
```swift
class CBPeripheralMock: CBPeripheralType {
    var delegate: CBPeripheralDelegate?
    var state: CBPeripheralState = .disconnected
}
```

I hope this helps.

**Comment by ferlopezm94** [comment]
Thanks @markspanbroek! But following that approach (using get), the error "Cannot assign to property: 'delegate' is a get-only property" appears when trying:

```self.peripheral!.delegate = self```

on a class that uses CBCentralManager and CBPeripheral.

**Comment by ferlopezm94** [comment]
@markspanbroek I fix that just setting: 
```var delegate: CBPeripheralDelegate? {get set}```

Thanks!

**Comment by markspanbroek** [comment]
Perfect! Good to hear that it works.

Closing the issue now.

**Comment by ferlopezm94** [comment]
When you're trying to tests the workflow using CoreBluetooth, for example, testing with the CBCentralManagerDelegate methods like:

```
func centralManager(_ central: CBCentralManager, didDiscover peripheral: CBPeripheral, advertisementData: [String : Any], rssi RSSI: NSNumber)
```

In this case we'll have to extract that in the protocol and change ```CBCentralManager``` to ```CBCentralManagerType```, right? If so, this could make the test files and our protocols files big, is there a workaround? Or what advise can you give me when trying to test a class that is both the CBCentralManagerDelegate and CBPeripheralDelegate.

**Comment by markspanbroek** [comment]
That's correct.

There is  a possible workaround if you're not really interested in the `central` parameter in the callback. You could call another function on your delegate from the `centralManager:didDiscover` method. You would then test invocations of that method instead.

**Comment by ferlopezm94** [comment]
But if you use the peripheral, the advertisementData and rssi, you have to fake all of those, right? So, it seems very complicated :/ and a lot of time invested.

**Comment by markspanbroek** [comment]
That's correct. I never said it would be easy ;)
